/*
 *	This file is generated by script PS_Exporter
 *	Please Do Not Modify it manually
 *	Author : dotboy
 */
 
#include "cocos2d.h"
#include "ui/UIButton.h"
#include "extensions/cocos-ext.h"

USING_NS_CC;
USING_NS_CC_EXT;
using namespace ui;
 
class <className>:public Layer
{
protected:
<def>
public:
	virtual bool init() {
		if( !Layer::init()){
			return false;
		}
